name: setup and cache action
description: 'A composite action to demonstrate usage of composite actions in GitHub Actions'
inputs:
  caching:
    description: "Enable/disable repositories caching"
    required: false
    default: 'true'
outputs:
  cache-used:
    description: Whether the cache was used or not
    value: ${{ steps.permission.outputs.returnValue }}

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.5'
        cache-read-only: false

    - name: Change gradle permission
      id: permission
      run: chmod +x ./gradlew
      # whenever 'run' property is used, we need to define in which prompt the run command to execute. selecting 'bash'
      shell: bash

      # Adding of hardcoded value to the github output space. It can be replaced with gha expression value
    - name: Setup action output
      run: echo "returnValue='Himanshu'" >> $GITHUB_OUTPUT
      shell: bash

    - name: Caching Gradle Dependencies
      if: inputs.caching == 'true'
      id: cache-gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
