name: "Spring Boot Gradle Build Action"
description: "Builds a Spring Boot project using Gradle inside Docker"
author: "Himanshu"

inputs:
  java-version:
    description: "Java version to use"
    default: "21"

outputs:
  artifact_path:
    description: "Path to the built Spring Boot JAR"

runs:
  using: "docker"
  image: "Dockerfile"