name: CI/CD for application

on:
  schedule:
    - cron: 0 0 * * SUN
  workflow_dispatch:
    inputs:
      message:
        description: "Reason for manually triggering the build"
        required: true

jobs:
  run-hello-word:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

